name: terminusdb-binder

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bqplot
  - ipycytoscape
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab >=2.2,<3
  - matplotlib-base
  - nbgitpuller
  - nodejs >=14,<15
  - pandas
  - pip
  - pyld
  - pyshacl
  - python >=3.8,<3.9
  - python-dateutil
  - rdflib-jsonld
  - requests
  - rust
  - w3lib
  - pip:
    - terminusdb-client
    - pyswip
    - csvs
    - extruct
